void BGi();
void HSv();
void rainbow();
void ticks();
void drumKit();
void ARGB();
void funfetti();
void bell();
void mouth();
void addGlitter();
void sinelon();
void juggle();
void setRGB();
void fairyFire();
void callPatterns();
void nextPattern();
void clipLen(uint8_t *ledStart, uint8_t *ledLen);
void querySerial();
void mask_by_IR();
void mask_by_position();
void LEDFillMask(uint32_t, uint32_t, bool);
void LEDApplyMask();
void FastLEDShowMask();
void sendVals();
void readXZ();
void readAnalog();
void measure_mpu6050(void);
