void BGi();
void rainbow();
void confetti();
void rainbowWithGlitter();
void sinelon();
void juggle();
void bpm();
void callPatterns();
//void nextPattern();
void clipLen(uint8_t *ledStart, uint8_t *ledLen);
void querySerial();
